language: node_js

node_js:
  - 10

cache:
  directories:
    - ~/.npm

install:
  - npm ci

deploy:
  provider: script
  skip_cleanup: true
  script: .travis/pu.sh
  on:
    branch: test
    tags: false
