language: node_js

node_js:
  - 10

cache: npm

install:
  - npm ci

deploy:
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      branch: test
      tags: true
  - provider: script
    script: chmod +x .travis/pu.sh && .travis/pu.sh
    skip_cleanup: true
    on:
      branch: test
      tags: false
