defaults: &defaults
  docker:
    - image: circleci/node:10.15.3

version: 2
jobs:
  upgrade-rc-version:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Set configuration
          command: git config --global user.email "$GITHUB_AUTHOR_EMAIL" && git config --global user.name "$GITHUB_AUTHOR_NAME"

      - run:
          name: Upgrade version
          command: npm version prerelease --preid=rc -m "upgrade version [ci skip]"

      - run:
          name: Push upgraded version
          command: git push https://$GITHUB_TOKEN@github.com/silevis/reactgrid.git develop

  upgrade-version-and-publish:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps-

      - run:
          name: Remove suffix from package version
          command: npm run remove-suffix

      - run: 
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "package.json" }}

      - run:
          name: Build TypeScript code
          command: npm run pre-deploy

      - run:
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: Publish to NPM
          command: npm publish --access=public

      - run:
          name: Set configuration
          command: git config --global user.email "$GITHUB_AUTHOR_EMAIL" && git config --global user.name "$GITHUB_AUTHOR_NAME"

      - run:
          name: Add changes
          command: git add .

      - run:
          name: Commit updated package version
          command: git commit -m "upgrade version [ci skip]"

      - run:
          name: Push upgraded version
          command: git push https://$GITHUB_TOKEN@github.com/silevis/reactgrid.git master

      - run:
          name: Change branch to develop
          command: git checkout develop

      - run:
          name: Remove suffix from develop package version
          command: npm run remove-suffix

      - run: 
          name: Update package-lock.json
          command: npm install

      - run:
          name: Add changes
          command: git add .

      - run:
          name: Commit updated package version
          command: git commit -m "upgrade version [ci skip]"

      - run:
          name: Push upgraded version
          command: git push https://$GITHUB_TOKEN@github.com/silevis/reactgrid.git develop
          
workflows:
  version: 2
  main:
    jobs:
      - upgrade-version-and-publish:
          filters:
            branches:
              only: master
      - upgrade-rc-version:
          filters:
            branches:
              only: develop
